// Generated by tools/frontend/generate_cpp_frontend_client.py. Do not edit.
#ifndef AI_OPENAI_CODEX_FRONTEND_CLIENT_ACCOUNTS_H
#define AI_OPENAI_CODEX_FRONTEND_CLIENT_ACCOUNTS_H

#include "ai/openai/codex/frontend/client/Export.h"
#include "ai/openai/codex/frontend/client/Results.h"
#include "ai/openai/codex/typed/Accounts.h"
#include "ai/openai/codex/typed/Results.h"

// clang-format off
namespace ai::openai::codex::frontend::client {
    class Client;

    class AISUITE_OPENAI_CODEX_FRONTEND_CLIENT_EXPORT Accounts {
    public:
        Accounts(const Accounts&) = delete;
        Accounts(Accounts&&) = delete;
        Accounts& operator=(const Accounts&) = delete;
        Accounts& operator=(Accounts&&) = delete;

        [[nodiscard]] Submission cancelLogin(::ai::openai::codex::typed::CancelLoginAccountParams parameters, CompletionHandler<::ai::openai::codex::typed::CancelLoginAccountResponse> handler);
        [[nodiscard]] Submission startLogin(::ai::openai::codex::typed::LoginAccountParams parameters, CompletionHandler<::ai::openai::codex::typed::LoginAccountResponse> handler);
        [[nodiscard]] Submission logout(DoneHandler handler);
        [[nodiscard]] Submission consumeRateLimitResetCredit(::ai::openai::codex::typed::ConsumeAccountRateLimitResetCreditParams parameters, CompletionHandler<::ai::openai::codex::typed::ConsumeAccountRateLimitResetCreditResponse> handler);
        [[nodiscard]] Submission readRateLimits(CompletionHandler<::ai::openai::codex::typed::GetAccountRateLimitsResponse> handler);
        [[nodiscard]] Submission read(::ai::openai::codex::typed::GetAccountParams parameters, CompletionHandler<::ai::openai::codex::typed::GetAccountResponse> handler);
        [[nodiscard]] Submission sendAddCreditsNudgeEmail(::ai::openai::codex::typed::SendAddCreditsNudgeEmailParams parameters, CompletionHandler<::ai::openai::codex::typed::SendAddCreditsNudgeEmailResponse> handler);
        [[nodiscard]] Submission readUsage(CompletionHandler<::ai::openai::codex::typed::GetAccountTokenUsageResponse> handler);
        [[nodiscard]] Submission readWorkspaceMessages(CompletionHandler<::ai::openai::codex::typed::GetWorkspaceMessagesResponse> handler);

    private:
        friend class Client;
        explicit Accounts(Client& owner) noexcept
            : client(&owner) {
        }
        Client* client;
    };
} // namespace ai::openai::codex::frontend::client
// clang-format on

#endif // AI_OPENAI_CODEX_FRONTEND_CLIENT_ACCOUNTS_H
