// Generated by tools/frontend/generate_cpp_frontend_client.py. Do not edit.
#ifndef AI_OPENAI_CODEX_FRONTEND_CLIENT_APPS_H
#define AI_OPENAI_CODEX_FRONTEND_CLIENT_APPS_H

#include "ai/openai/codex/frontend/client/Export.h"
#include "ai/openai/codex/frontend/client/Results.h"
#include "ai/openai/codex/typed/Apps.h"

// clang-format off
namespace ai::openai::codex::frontend::client {
    class Client;

    class AISUITE_OPENAI_CODEX_FRONTEND_CLIENT_EXPORT Apps {
    public:
        Apps(const Apps&) = delete;
        Apps(Apps&&) = delete;
        Apps& operator=(const Apps&) = delete;
        Apps& operator=(Apps&&) = delete;

        [[nodiscard]] Submission list(::ai::openai::codex::typed::AppsListParams parameters, CompletionHandler<::ai::openai::codex::typed::AppsListResponse> handler);

    private:
        friend class Client;
        explicit Apps(Client& owner) noexcept
            : client(&owner) {
        }
        Client* client;
    };
} // namespace ai::openai::codex::frontend::client
// clang-format on

#endif // AI_OPENAI_CODEX_FRONTEND_CLIENT_APPS_H
