// Generated by tools/frontend/generate_cpp_frontend_client.py. Do not edit.
#ifndef AI_OPENAI_CODEX_FRONTEND_CLIENT_COMMANDS_H
#define AI_OPENAI_CODEX_FRONTEND_CLIENT_COMMANDS_H

#include "ai/openai/codex/frontend/client/Export.h"
#include "ai/openai/codex/frontend/client/Results.h"
#include "ai/openai/codex/typed/Commands.h"
#include "ai/openai/codex/typed/Results.h"

// clang-format off
namespace ai::openai::codex::frontend::client {
    class Client;

    class AISUITE_OPENAI_CODEX_FRONTEND_CLIENT_EXPORT Commands {
    public:
        Commands(const Commands&) = delete;
        Commands(Commands&&) = delete;
        Commands& operator=(const Commands&) = delete;
        Commands& operator=(Commands&&) = delete;

        [[nodiscard]] Submission exec(::ai::openai::codex::typed::CommandExecParams parameters, CompletionHandler<::ai::openai::codex::typed::CommandExecResponse> handler);
        [[nodiscard]] Submission resize(::ai::openai::codex::typed::CommandExecResizeParams parameters, DoneHandler handler);
        [[nodiscard]] Submission terminate(::ai::openai::codex::typed::CommandExecTerminateParams parameters, DoneHandler handler);
        [[nodiscard]] Submission write(::ai::openai::codex::typed::CommandExecWriteParams parameters, DoneHandler handler);

    private:
        friend class Client;
        explicit Commands(Client& owner) noexcept
            : client(&owner) {
        }
        Client* client;
    };
} // namespace ai::openai::codex::frontend::client
// clang-format on

#endif // AI_OPENAI_CODEX_FRONTEND_CLIENT_COMMANDS_H
