// Generated by tools/frontend/generate_cpp_frontend_client.py. Do not edit.
#ifndef AI_OPENAI_CODEX_FRONTEND_CLIENT_CONFIGURATION_H
#define AI_OPENAI_CODEX_FRONTEND_CLIENT_CONFIGURATION_H

#include "ai/openai/codex/frontend/client/Export.h"
#include "ai/openai/codex/frontend/client/Results.h"
#include "ai/openai/codex/typed/Configuration.h"
#include "ai/openai/codex/typed/Results.h"

// clang-format off
namespace ai::openai::codex::frontend::client {
    class Client;

    class AISUITE_OPENAI_CODEX_FRONTEND_CLIENT_EXPORT Configuration {
    public:
        Configuration(const Configuration&) = delete;
        Configuration(Configuration&&) = delete;
        Configuration& operator=(const Configuration&) = delete;
        Configuration& operator=(Configuration&&) = delete;

        [[nodiscard]] Submission batchWrite(::ai::openai::codex::typed::ConfigBatchWriteParams parameters, CompletionHandler<::ai::openai::codex::typed::ConfigWriteResponse> handler);
        [[nodiscard]] Submission reloadMcpServers(DoneHandler handler);
        [[nodiscard]] Submission read(::ai::openai::codex::typed::ConfigReadParams parameters, CompletionHandler<::ai::openai::codex::typed::ConfigReadResponse> handler);
        [[nodiscard]] Submission writeValue(::ai::openai::codex::typed::ConfigValueWriteParams parameters, CompletionHandler<::ai::openai::codex::typed::ConfigWriteResponse> handler);
        [[nodiscard]] Submission readRequirements(CompletionHandler<::ai::openai::codex::typed::ConfigRequirementsReadResponse> handler);
        [[nodiscard]] Submission setExperimentalFeatureEnablement(::ai::openai::codex::typed::ExperimentalFeatureEnablementSetParams parameters, CompletionHandler<::ai::openai::codex::typed::ExperimentalFeatureEnablementSetResponse> handler);
        [[nodiscard]] Submission listExperimentalFeatures(::ai::openai::codex::typed::ExperimentalFeatureListParams parameters, CompletionHandler<::ai::openai::codex::typed::ExperimentalFeatureListResponse> handler);

    private:
        friend class Client;
        explicit Configuration(Client& owner) noexcept
            : client(&owner) {
        }
        Client* client;
    };
} // namespace ai::openai::codex::frontend::client
// clang-format on

#endif // AI_OPENAI_CODEX_FRONTEND_CLIENT_CONFIGURATION_H
