/*
 * SPDX-License-Identifier: LGPL-3.0-or-later OR MIT
 */

#ifndef AI_OPENAI_CODEX_FRONTEND_CLIENT_EXPORT_H
#define AI_OPENAI_CODEX_FRONTEND_CLIENT_EXPORT_H

#if defined(_WIN32) || defined(__CYGWIN__)
#if defined(AISUITE_OPENAI_CODEX_FRONTEND_CLIENT_STATIC_DEFINE)
#define AISUITE_OPENAI_CODEX_FRONTEND_CLIENT_EXPORT
#elif defined(AISUITE_OPENAI_CODEX_FRONTEND_CLIENT_BUILDING_LIBRARY)
#define AISUITE_OPENAI_CODEX_FRONTEND_CLIENT_EXPORT __declspec(dllexport)
#else
#define AISUITE_OPENAI_CODEX_FRONTEND_CLIENT_EXPORT __declspec(dllimport)
#endif
#define AISUITE_OPENAI_CODEX_FRONTEND_CLIENT_NO_EXPORT
#elif defined(__GNUC__) && __GNUC__ >= 4
#define AISUITE_OPENAI_CODEX_FRONTEND_CLIENT_EXPORT __attribute__((visibility("default")))
#define AISUITE_OPENAI_CODEX_FRONTEND_CLIENT_NO_EXPORT __attribute__((visibility("hidden")))
#else
#define AISUITE_OPENAI_CODEX_FRONTEND_CLIENT_EXPORT
#define AISUITE_OPENAI_CODEX_FRONTEND_CLIENT_NO_EXPORT
#endif

#endif // AI_OPENAI_CODEX_FRONTEND_CLIENT_EXPORT_H
