// Generated by tools/frontend/generate_cpp_frontend_client.py. Do not edit.
#ifndef AI_OPENAI_CODEX_FRONTEND_CLIENT_EXTERNALAGENTS_H
#define AI_OPENAI_CODEX_FRONTEND_CLIENT_EXTERNALAGENTS_H

#include "ai/openai/codex/frontend/client/Export.h"
#include "ai/openai/codex/frontend/client/Results.h"
#include "ai/openai/codex/typed/ExternalAgents.h"
#include "ai/openai/codex/typed/Results.h"

// clang-format off
namespace ai::openai::codex::frontend::client {
    class Client;

    class AISUITE_OPENAI_CODEX_FRONTEND_CLIENT_EXPORT ExternalAgents {
    public:
        ExternalAgents(const ExternalAgents&) = delete;
        ExternalAgents(ExternalAgents&&) = delete;
        ExternalAgents& operator=(const ExternalAgents&) = delete;
        ExternalAgents& operator=(ExternalAgents&&) = delete;

        [[nodiscard]] Submission detect(::ai::openai::codex::typed::ExternalAgentConfigDetectParams parameters, CompletionHandler<::ai::openai::codex::typed::ExternalAgentConfigDetectResponse> handler);
        [[nodiscard]] Submission importConfiguration(::ai::openai::codex::typed::ExternalAgentConfigImportParams parameters, CompletionHandler<::ai::openai::codex::typed::ExternalAgentConfigImportResponse> handler);
        [[nodiscard]] Submission readImportHistories(CompletionHandler<::ai::openai::codex::typed::ExternalAgentConfigImportHistoriesReadResponse> handler);

    private:
        friend class Client;
        explicit ExternalAgents(Client& owner) noexcept
            : client(&owner) {
        }
        Client* client;
    };
} // namespace ai::openai::codex::frontend::client
// clang-format on

#endif // AI_OPENAI_CODEX_FRONTEND_CLIENT_EXTERNALAGENTS_H
