// Generated by tools/frontend/generate_cpp_frontend_client.py. Do not edit.
#ifndef AI_OPENAI_CODEX_FRONTEND_CLIENT_FEEDBACK_H
#define AI_OPENAI_CODEX_FRONTEND_CLIENT_FEEDBACK_H

#include "ai/openai/codex/frontend/client/Export.h"
#include "ai/openai/codex/frontend/client/Results.h"
#include "ai/openai/codex/typed/Feedback.h"

// clang-format off
namespace ai::openai::codex::frontend::client {
    class Client;

    class AISUITE_OPENAI_CODEX_FRONTEND_CLIENT_EXPORT Feedback {
    public:
        Feedback(const Feedback&) = delete;
        Feedback(Feedback&&) = delete;
        Feedback& operator=(const Feedback&) = delete;
        Feedback& operator=(Feedback&&) = delete;

        [[nodiscard]] Submission upload(::ai::openai::codex::typed::FeedbackUploadParams parameters, CompletionHandler<::ai::openai::codex::typed::FeedbackUploadResponse> handler);

    private:
        friend class Client;
        explicit Feedback(Client& owner) noexcept
            : client(&owner) {
        }
        Client* client;
    };
} // namespace ai::openai::codex::frontend::client
// clang-format on

#endif // AI_OPENAI_CODEX_FRONTEND_CLIENT_FEEDBACK_H
