// Generated by tools/frontend/generate_cpp_frontend_client.py. Do not edit.
#ifndef AI_OPENAI_CODEX_FRONTEND_CLIENT_FILESYSTEM_H
#define AI_OPENAI_CODEX_FRONTEND_CLIENT_FILESYSTEM_H

#include "ai/openai/codex/frontend/client/Export.h"
#include "ai/openai/codex/frontend/client/Results.h"
#include "ai/openai/codex/typed/Filesystem.h"
#include "ai/openai/codex/typed/Results.h"

// clang-format off
namespace ai::openai::codex::frontend::client {
    class Client;

    class AISUITE_OPENAI_CODEX_FRONTEND_CLIENT_EXPORT Filesystem {
    public:
        Filesystem(const Filesystem&) = delete;
        Filesystem(Filesystem&&) = delete;
        Filesystem& operator=(const Filesystem&) = delete;
        Filesystem& operator=(Filesystem&&) = delete;

        [[nodiscard]] Submission copy(::ai::openai::codex::typed::FsCopyParams parameters, DoneHandler handler);
        [[nodiscard]] Submission createDirectory(::ai::openai::codex::typed::FsCreateDirectoryParams parameters, DoneHandler handler);
        [[nodiscard]] Submission getMetadata(::ai::openai::codex::typed::FsGetMetadataParams parameters, CompletionHandler<::ai::openai::codex::typed::FsGetMetadataResponse> handler);
        [[nodiscard]] Submission readDirectory(::ai::openai::codex::typed::FsReadDirectoryParams parameters, CompletionHandler<::ai::openai::codex::typed::FsReadDirectoryResponse> handler);
        [[nodiscard]] Submission readFile(::ai::openai::codex::typed::FsReadFileParams parameters, CompletionHandler<::ai::openai::codex::typed::FsReadFileResponse> handler);
        [[nodiscard]] Submission remove(::ai::openai::codex::typed::FsRemoveParams parameters, DoneHandler handler);
        [[nodiscard]] Submission unwatch(::ai::openai::codex::typed::FsUnwatchParams parameters, DoneHandler handler);
        [[nodiscard]] Submission watch(::ai::openai::codex::typed::FsWatchParams parameters, CompletionHandler<::ai::openai::codex::typed::FsWatchResponse> handler);
        [[nodiscard]] Submission writeFile(::ai::openai::codex::typed::FsWriteFileParams parameters, DoneHandler handler);
        [[nodiscard]] Submission fuzzyFileSearch(::ai::openai::codex::typed::FuzzyFileSearchParams parameters, CompletionHandler<::ai::openai::codex::typed::FuzzyFileSearchResponse> handler);

    private:
        friend class Client;
        explicit Filesystem(Client& owner) noexcept
            : client(&owner) {
        }
        Client* client;
    };
} // namespace ai::openai::codex::frontend::client
// clang-format on

#endif // AI_OPENAI_CODEX_FRONTEND_CLIENT_FILESYSTEM_H
