// Generated by tools/frontend/generate_cpp_frontend_client.py. Do not edit.
#ifndef AI_OPENAI_CODEX_FRONTEND_CLIENT_HOOKS_H
#define AI_OPENAI_CODEX_FRONTEND_CLIENT_HOOKS_H

#include "ai/openai/codex/frontend/client/Export.h"
#include "ai/openai/codex/frontend/client/Results.h"
#include "ai/openai/codex/typed/Hooks.h"

// clang-format off
namespace ai::openai::codex::frontend::client {
    class Client;

    class AISUITE_OPENAI_CODEX_FRONTEND_CLIENT_EXPORT Hooks {
    public:
        Hooks(const Hooks&) = delete;
        Hooks(Hooks&&) = delete;
        Hooks& operator=(const Hooks&) = delete;
        Hooks& operator=(Hooks&&) = delete;

        [[nodiscard]] Submission list(::ai::openai::codex::typed::HooksListParams parameters, CompletionHandler<::ai::openai::codex::typed::HooksListResponse> handler);

    private:
        friend class Client;
        explicit Hooks(Client& owner) noexcept
            : client(&owner) {
        }
        Client* client;
    };
} // namespace ai::openai::codex::frontend::client
// clang-format on

#endif // AI_OPENAI_CODEX_FRONTEND_CLIENT_HOOKS_H
