// Generated by tools/frontend/generate_cpp_frontend_client.py. Do not edit.
#ifndef AI_OPENAI_CODEX_FRONTEND_CLIENT_MARKETPLACE_H
#define AI_OPENAI_CODEX_FRONTEND_CLIENT_MARKETPLACE_H

#include "ai/openai/codex/frontend/client/Export.h"
#include "ai/openai/codex/frontend/client/Results.h"
#include "ai/openai/codex/typed/Marketplace.h"

// clang-format off
namespace ai::openai::codex::frontend::client {
    class Client;

    class AISUITE_OPENAI_CODEX_FRONTEND_CLIENT_EXPORT Marketplace {
    public:
        Marketplace(const Marketplace&) = delete;
        Marketplace(Marketplace&&) = delete;
        Marketplace& operator=(const Marketplace&) = delete;
        Marketplace& operator=(Marketplace&&) = delete;

        [[nodiscard]] Submission add(::ai::openai::codex::typed::MarketplaceAddParams parameters, CompletionHandler<::ai::openai::codex::typed::MarketplaceAddResponse> handler);
        [[nodiscard]] Submission remove(::ai::openai::codex::typed::MarketplaceRemoveParams parameters, CompletionHandler<::ai::openai::codex::typed::MarketplaceRemoveResponse> handler);
        [[nodiscard]] Submission upgrade(::ai::openai::codex::typed::MarketplaceUpgradeParams parameters, CompletionHandler<::ai::openai::codex::typed::MarketplaceUpgradeResponse> handler);

    private:
        friend class Client;
        explicit Marketplace(Client& owner) noexcept
            : client(&owner) {
        }
        Client* client;
    };
} // namespace ai::openai::codex::frontend::client
// clang-format on

#endif // AI_OPENAI_CODEX_FRONTEND_CLIENT_MARKETPLACE_H
