// Generated by tools/frontend/generate_cpp_frontend_client.py. Do not edit.
#ifndef AI_OPENAI_CODEX_FRONTEND_CLIENT_MCP_H
#define AI_OPENAI_CODEX_FRONTEND_CLIENT_MCP_H

#include "ai/openai/codex/frontend/client/Export.h"
#include "ai/openai/codex/frontend/client/Results.h"
#include "ai/openai/codex/typed/Mcp.h"

// clang-format off
namespace ai::openai::codex::frontend::client {
    class Client;

    class AISUITE_OPENAI_CODEX_FRONTEND_CLIENT_EXPORT Mcp {
    public:
        Mcp(const Mcp&) = delete;
        Mcp(Mcp&&) = delete;
        Mcp& operator=(const Mcp&) = delete;
        Mcp& operator=(Mcp&&) = delete;

        [[nodiscard]] Submission startOauthLogin(::ai::openai::codex::typed::McpServerOauthLoginParams parameters, CompletionHandler<::ai::openai::codex::typed::McpServerOauthLoginResponse> handler);
        [[nodiscard]] Submission readResource(::ai::openai::codex::typed::McpResourceReadParams parameters, CompletionHandler<::ai::openai::codex::typed::McpResourceReadResponse> handler);
        [[nodiscard]] Submission callTool(::ai::openai::codex::typed::McpServerToolCallParams parameters, CompletionHandler<::ai::openai::codex::typed::McpServerToolCallResponse> handler);
        [[nodiscard]] Submission listServers(::ai::openai::codex::typed::ListMcpServerStatusParams parameters, CompletionHandler<::ai::openai::codex::typed::ListMcpServerStatusResponse> handler);

    private:
        friend class Client;
        explicit Mcp(Client& owner) noexcept
            : client(&owner) {
        }
        Client* client;
    };
} // namespace ai::openai::codex::frontend::client
// clang-format on

#endif // AI_OPENAI_CODEX_FRONTEND_CLIENT_MCP_H
