// Generated by tools/frontend/generate_cpp_frontend_client.py. Do not edit.
#ifndef AI_OPENAI_CODEX_FRONTEND_CLIENT_MODELS_H
#define AI_OPENAI_CODEX_FRONTEND_CLIENT_MODELS_H

#include "ai/openai/codex/frontend/client/Export.h"
#include "ai/openai/codex/frontend/client/Results.h"
#include "ai/openai/codex/typed/Models.h"

// clang-format off
namespace ai::openai::codex::frontend::client {
    class Client;

    class AISUITE_OPENAI_CODEX_FRONTEND_CLIENT_EXPORT Models {
    public:
        Models(const Models&) = delete;
        Models(Models&&) = delete;
        Models& operator=(const Models&) = delete;
        Models& operator=(Models&&) = delete;

        [[nodiscard]] Submission list(::ai::openai::codex::typed::ModelListParams parameters, CompletionHandler<::ai::openai::codex::typed::ModelListResponse> handler);
        [[nodiscard]] Submission readProviderCapabilities(::ai::openai::codex::typed::ModelProviderCapabilitiesReadParams parameters, CompletionHandler<::ai::openai::codex::typed::ModelProviderCapabilitiesReadResponse> handler);

    private:
        friend class Client;
        explicit Models(Client& owner) noexcept
            : client(&owner) {
        }
        Client* client;
    };
} // namespace ai::openai::codex::frontend::client
// clang-format on

#endif // AI_OPENAI_CODEX_FRONTEND_CLIENT_MODELS_H
