// Generated by tools/frontend/generate_cpp_frontend_client.py. Do not edit.
#ifndef AI_OPENAI_CODEX_FRONTEND_CLIENT_PERMISSIONPROFILES_H
#define AI_OPENAI_CODEX_FRONTEND_CLIENT_PERMISSIONPROFILES_H

#include "ai/openai/codex/frontend/client/Export.h"
#include "ai/openai/codex/frontend/client/Results.h"
#include "ai/openai/codex/typed/PermissionProfiles.h"

// clang-format off
namespace ai::openai::codex::frontend::client {
    class Client;

    class AISUITE_OPENAI_CODEX_FRONTEND_CLIENT_EXPORT PermissionProfiles {
    public:
        PermissionProfiles(const PermissionProfiles&) = delete;
        PermissionProfiles(PermissionProfiles&&) = delete;
        PermissionProfiles& operator=(const PermissionProfiles&) = delete;
        PermissionProfiles& operator=(PermissionProfiles&&) = delete;

        [[nodiscard]] Submission list(::ai::openai::codex::typed::PermissionProfileListParams parameters, CompletionHandler<::ai::openai::codex::typed::PermissionProfileListResponse> handler);

    private:
        friend class Client;
        explicit PermissionProfiles(Client& owner) noexcept
            : client(&owner) {
        }
        Client* client;
    };
} // namespace ai::openai::codex::frontend::client
// clang-format on

#endif // AI_OPENAI_CODEX_FRONTEND_CLIENT_PERMISSIONPROFILES_H
