// Generated by tools/frontend/generate_cpp_frontend_client.py. Do not edit.
#ifndef AI_OPENAI_CODEX_FRONTEND_CLIENT_PLUGINS_H
#define AI_OPENAI_CODEX_FRONTEND_CLIENT_PLUGINS_H

#include "ai/openai/codex/frontend/client/Export.h"
#include "ai/openai/codex/frontend/client/Results.h"
#include "ai/openai/codex/typed/Plugins.h"
#include "ai/openai/codex/typed/Results.h"

// clang-format off
namespace ai::openai::codex::frontend::client {
    class Client;

    class AISUITE_OPENAI_CODEX_FRONTEND_CLIENT_EXPORT Plugins {
    public:
        Plugins(const Plugins&) = delete;
        Plugins(Plugins&&) = delete;
        Plugins& operator=(const Plugins&) = delete;
        Plugins& operator=(Plugins&&) = delete;

        [[nodiscard]] Submission install(::ai::openai::codex::typed::PluginInstallParams parameters, CompletionHandler<::ai::openai::codex::typed::PluginInstallResponse> handler);
        [[nodiscard]] Submission installed(::ai::openai::codex::typed::PluginInstalledParams parameters, CompletionHandler<::ai::openai::codex::typed::PluginInstalledResponse> handler);
        [[nodiscard]] Submission list(::ai::openai::codex::typed::PluginListParams parameters, CompletionHandler<::ai::openai::codex::typed::PluginListResponse> handler);
        [[nodiscard]] Submission read(::ai::openai::codex::typed::PluginReadParams parameters, CompletionHandler<::ai::openai::codex::typed::PluginReadResponse> handler);
        [[nodiscard]] Submission shareCheckout(::ai::openai::codex::typed::PluginShareCheckoutParams parameters, CompletionHandler<::ai::openai::codex::typed::PluginShareCheckoutResponse> handler);
        [[nodiscard]] Submission shareDelete(::ai::openai::codex::typed::PluginShareDeleteParams parameters, DoneHandler handler);
        [[nodiscard]] Submission shareList(::ai::openai::codex::typed::PluginShareListParams parameters, CompletionHandler<::ai::openai::codex::typed::PluginShareListResponse> handler);
        [[nodiscard]] Submission shareSave(::ai::openai::codex::typed::PluginShareSaveParams parameters, CompletionHandler<::ai::openai::codex::typed::PluginShareSaveResponse> handler);
        [[nodiscard]] Submission shareUpdateTargets(::ai::openai::codex::typed::PluginShareUpdateTargetsParams parameters, CompletionHandler<::ai::openai::codex::typed::PluginShareUpdateTargetsResponse> handler);
        [[nodiscard]] Submission readSkill(::ai::openai::codex::typed::PluginSkillReadParams parameters, CompletionHandler<::ai::openai::codex::typed::PluginSkillReadResponse> handler);
        [[nodiscard]] Submission uninstall(::ai::openai::codex::typed::PluginUninstallParams parameters, DoneHandler handler);

    private:
        friend class Client;
        explicit Plugins(Client& owner) noexcept
            : client(&owner) {
        }
        Client* client;
    };
} // namespace ai::openai::codex::frontend::client
// clang-format on

#endif // AI_OPENAI_CODEX_FRONTEND_CLIENT_PLUGINS_H
