// Generated by tools/frontend/generate_cpp_frontend_client.py. Do not edit.
#ifndef AI_OPENAI_CODEX_FRONTEND_CLIENT_REQUESTS_H
#define AI_OPENAI_CODEX_FRONTEND_CLIENT_REQUESTS_H

#include "ai/openai/codex/frontend/client/Export.h"
#include "ai/openai/codex/frontend/client/Results.h"
#include "ai/openai/codex/frontend/client/Types.h"
#include "ai/openai/codex/typed/Results.h"

// clang-format off
namespace ai::openai::codex::frontend::client {
    class Client;

    class AISUITE_OPENAI_CODEX_FRONTEND_CLIENT_EXPORT Requests {
    public:
        Requests(const Requests&) = delete;
        Requests(Requests&&) = delete;
        Requests& operator=(const Requests&) = delete;
        Requests& operator=(Requests&&) = delete;

        [[nodiscard]] Submission respond(::ai::openai::codex::frontend::client::ApprovalRespondParams parameters, DoneHandler handler);
        [[nodiscard]] Submission respond(::ai::openai::codex::frontend::client::UserInputRespondParams parameters, DoneHandler handler);
        [[nodiscard]] Submission respond(::ai::openai::codex::frontend::client::AuthenticationRespondParams parameters, DoneHandler handler);
        [[nodiscard]] Submission respond(::ai::openai::codex::frontend::client::UnknownRequestRespondParams parameters, DoneHandler handler);
        [[nodiscard]] Submission reject(::ai::openai::codex::frontend::client::UnknownRequestRejectParams parameters, DoneHandler handler);
        [[nodiscard]] Submission respond(::ai::openai::codex::frontend::client::ApplyPatchApprovalRespondParams parameters, DoneHandler handler);
        [[nodiscard]] Submission respond(::ai::openai::codex::frontend::client::AttestationRespondParams parameters, DoneHandler handler);
        [[nodiscard]] Submission respond(::ai::openai::codex::frontend::client::DynamicToolRespondParams parameters, DoneHandler handler);
        [[nodiscard]] Submission respond(::ai::openai::codex::frontend::client::ExecCommandApprovalRespondParams parameters, DoneHandler handler);
        [[nodiscard]] Submission reject(::ai::openai::codex::frontend::client::KnownRequestRejectParams parameters, DoneHandler handler);
        [[nodiscard]] Submission respond(::ai::openai::codex::frontend::client::McpElicitationRespondParams parameters, DoneHandler handler);
        [[nodiscard]] Submission respond(::ai::openai::codex::frontend::client::PermissionsApprovalRespondParams parameters, DoneHandler handler);

    private:
        friend class Client;
        explicit Requests(Client& owner) noexcept
            : client(&owner) {
        }
        Client* client;
    };
} // namespace ai::openai::codex::frontend::client
// clang-format on

#endif // AI_OPENAI_CODEX_FRONTEND_CLIENT_REQUESTS_H
