// Generated by tools/frontend/generate_cpp_frontend_client.py. Do not edit.
#ifndef AI_OPENAI_CODEX_FRONTEND_CLIENT_REVIEWS_H
#define AI_OPENAI_CODEX_FRONTEND_CLIENT_REVIEWS_H

#include "ai/openai/codex/frontend/client/Export.h"
#include "ai/openai/codex/frontend/client/Results.h"
#include "ai/openai/codex/typed/Reviews.h"

// clang-format off
namespace ai::openai::codex::frontend::client {
    class Client;

    class AISUITE_OPENAI_CODEX_FRONTEND_CLIENT_EXPORT Reviews {
    public:
        Reviews(const Reviews&) = delete;
        Reviews(Reviews&&) = delete;
        Reviews& operator=(const Reviews&) = delete;
        Reviews& operator=(Reviews&&) = delete;

        [[nodiscard]] Submission start(::ai::openai::codex::typed::ReviewStartParams parameters, CompletionHandler<::ai::openai::codex::typed::ReviewStartResponse> handler);

    private:
        friend class Client;
        explicit Reviews(Client& owner) noexcept
            : client(&owner) {
        }
        Client* client;
    };
} // namespace ai::openai::codex::frontend::client
// clang-format on

#endif // AI_OPENAI_CODEX_FRONTEND_CLIENT_REVIEWS_H
