// Generated by tools/frontend/generate_cpp_frontend_client.py. Do not edit.
#ifndef AI_OPENAI_CODEX_FRONTEND_CLIENT_SKILLS_H
#define AI_OPENAI_CODEX_FRONTEND_CLIENT_SKILLS_H

#include "ai/openai/codex/frontend/client/Export.h"
#include "ai/openai/codex/frontend/client/Results.h"
#include "ai/openai/codex/typed/Results.h"
#include "ai/openai/codex/typed/Skills.h"

// clang-format off
namespace ai::openai::codex::frontend::client {
    class Client;

    class AISUITE_OPENAI_CODEX_FRONTEND_CLIENT_EXPORT Skills {
    public:
        Skills(const Skills&) = delete;
        Skills(Skills&&) = delete;
        Skills& operator=(const Skills&) = delete;
        Skills& operator=(Skills&&) = delete;

        [[nodiscard]] Submission writeConfig(::ai::openai::codex::typed::SkillsConfigWriteParams parameters, CompletionHandler<::ai::openai::codex::typed::SkillsConfigWriteResponse> handler);
        [[nodiscard]] Submission setExtraRoots(::ai::openai::codex::typed::SkillsExtraRootsSetParams parameters, DoneHandler handler);
        [[nodiscard]] Submission list(::ai::openai::codex::typed::SkillsListParams parameters, CompletionHandler<::ai::openai::codex::typed::SkillsListResponse> handler);

    private:
        friend class Client;
        explicit Skills(Client& owner) noexcept
            : client(&owner) {
        }
        Client* client;
    };
} // namespace ai::openai::codex::frontend::client
// clang-format on

#endif // AI_OPENAI_CODEX_FRONTEND_CLIENT_SKILLS_H
