// Generated by tools/frontend/generate_cpp_frontend_client.py. Do not edit.
#ifndef AI_OPENAI_CODEX_FRONTEND_CLIENT_THREADS_H
#define AI_OPENAI_CODEX_FRONTEND_CLIENT_THREADS_H

#include "ai/openai/codex/frontend/client/Export.h"
#include "ai/openai/codex/frontend/client/Results.h"
#include "ai/openai/codex/typed/Results.h"
#include "ai/openai/codex/typed/Threads.h"

// clang-format off
namespace ai::openai::codex::frontend::client {
    class Client;

    class AISUITE_OPENAI_CODEX_FRONTEND_CLIENT_EXPORT Threads {
    public:
        Threads(const Threads&) = delete;
        Threads(Threads&&) = delete;
        Threads& operator=(const Threads&) = delete;
        Threads& operator=(Threads&&) = delete;

        [[nodiscard]] Submission start(::ai::openai::codex::typed::ThreadStartParams parameters, CompletionHandler<::ai::openai::codex::frontend::client::ThreadStartResult> handler);
        [[nodiscard]] Submission resume(::ai::openai::codex::typed::ThreadResumeParams parameters, CompletionHandler<::ai::openai::codex::frontend::client::ThreadResumeResult> handler);
        [[nodiscard]] Submission list(::ai::openai::codex::typed::ThreadListParams parameters, CompletionHandler<::ai::openai::codex::frontend::client::ThreadListResult> handler);
        [[nodiscard]] Submission read(::ai::openai::codex::typed::ThreadReadParams parameters, CompletionHandler<::ai::openai::codex::frontend::client::ThreadReadResult> handler);
        [[nodiscard]] Submission approveGuardianDeniedAction(::ai::openai::codex::typed::ThreadApproveGuardianDeniedActionParams parameters, DoneHandler handler);
        [[nodiscard]] Submission archive(::ai::openai::codex::typed::ThreadArchiveParams parameters, DoneHandler handler);
        [[nodiscard]] Submission startCompaction(::ai::openai::codex::typed::ThreadCompactStartParams parameters, DoneHandler handler);
        [[nodiscard]] Submission remove(::ai::openai::codex::typed::ThreadDeleteParams parameters, DoneHandler handler);
        [[nodiscard]] Submission fork(::ai::openai::codex::typed::ThreadForkParams parameters, CompletionHandler<::ai::openai::codex::typed::ThreadForkResponse> handler);
        [[nodiscard]] Submission clearGoal(::ai::openai::codex::typed::ThreadGoalClearParams parameters, CompletionHandler<::ai::openai::codex::typed::ThreadGoalClearResponse> handler);
        [[nodiscard]] Submission getGoal(::ai::openai::codex::typed::ThreadGoalGetParams parameters, CompletionHandler<::ai::openai::codex::typed::ThreadGoalGetResponse> handler);
        [[nodiscard]] Submission setGoal(::ai::openai::codex::typed::ThreadGoalSetParams parameters, CompletionHandler<::ai::openai::codex::typed::ThreadGoalSetResponse> handler);
        [[nodiscard]] Submission injectItems(::ai::openai::codex::typed::ThreadInjectItemsParams parameters, DoneHandler handler);
        [[nodiscard]] Submission listLoaded(::ai::openai::codex::typed::ThreadLoadedListParams parameters, CompletionHandler<::ai::openai::codex::typed::ThreadLoadedListResponse> handler);
        [[nodiscard]] Submission updateMetadata(::ai::openai::codex::typed::ThreadMetadataUpdateParams parameters, CompletionHandler<::ai::openai::codex::typed::ThreadMetadataUpdateResponse> handler);
        [[nodiscard]] Submission setName(::ai::openai::codex::typed::ThreadSetNameParams parameters, DoneHandler handler);
        [[nodiscard]] Submission rollback(::ai::openai::codex::typed::ThreadRollbackParams parameters, CompletionHandler<::ai::openai::codex::typed::ThreadRollbackResponse> handler);
        [[nodiscard]] Submission shellCommand(::ai::openai::codex::typed::ThreadShellCommandParams parameters, DoneHandler handler);
        [[nodiscard]] Submission unarchive(::ai::openai::codex::typed::ThreadUnarchiveParams parameters, CompletionHandler<::ai::openai::codex::typed::ThreadUnarchiveResponse> handler);
        [[nodiscard]] Submission unsubscribe(::ai::openai::codex::typed::ThreadUnsubscribeParams parameters, CompletionHandler<::ai::openai::codex::typed::ThreadUnsubscribeResponse> handler);

    private:
        friend class Client;
        explicit Threads(Client& owner) noexcept
            : client(&owner) {
        }
        Client* client;
    };
} // namespace ai::openai::codex::frontend::client
// clang-format on

#endif // AI_OPENAI_CODEX_FRONTEND_CLIENT_THREADS_H
