// Generated by tools/frontend/generate_cpp_frontend_client.py. Do not edit.
#ifndef AI_OPENAI_CODEX_FRONTEND_CLIENT_TURNS_H
#define AI_OPENAI_CODEX_FRONTEND_CLIENT_TURNS_H

#include "ai/openai/codex/frontend/client/Export.h"
#include "ai/openai/codex/frontend/client/Results.h"
#include "ai/openai/codex/typed/Results.h"
#include "ai/openai/codex/typed/Turns.h"

// clang-format off
namespace ai::openai::codex::frontend::client {
    class Client;

    class AISUITE_OPENAI_CODEX_FRONTEND_CLIENT_EXPORT Turns {
    public:
        Turns(const Turns&) = delete;
        Turns(Turns&&) = delete;
        Turns& operator=(const Turns&) = delete;
        Turns& operator=(Turns&&) = delete;

        [[nodiscard]] Submission start(::ai::openai::codex::typed::TurnStartParams parameters, CompletionHandler<::ai::openai::codex::frontend::client::TurnStartResult> handler);
        [[nodiscard]] Submission interrupt(::ai::openai::codex::typed::TurnInterruptParams parameters, DoneHandler handler);
        [[nodiscard]] Submission steer(::ai::openai::codex::typed::TurnSteerParams parameters, CompletionHandler<::ai::openai::codex::typed::TurnSteerResponse> handler);

    private:
        friend class Client;
        explicit Turns(Client& owner) noexcept
            : client(&owner) {
        }
        Client* client;
    };
} // namespace ai::openai::codex::frontend::client
// clang-format on

#endif // AI_OPENAI_CODEX_FRONTEND_CLIENT_TURNS_H
