// Generated by tools/frontend/generate_cpp_frontend_client.py. Do not edit.
#ifndef AI_OPENAI_CODEX_FRONTEND_CLIENT_WINDOWSSANDBOX_H
#define AI_OPENAI_CODEX_FRONTEND_CLIENT_WINDOWSSANDBOX_H

#include "ai/openai/codex/frontend/client/Export.h"
#include "ai/openai/codex/frontend/client/Results.h"
#include "ai/openai/codex/typed/Results.h"
#include "ai/openai/codex/typed/WindowsSandbox.h"

// clang-format off
namespace ai::openai::codex::frontend::client {
    class Client;

    class AISUITE_OPENAI_CODEX_FRONTEND_CLIENT_EXPORT WindowsSandbox {
    public:
        WindowsSandbox(const WindowsSandbox&) = delete;
        WindowsSandbox(WindowsSandbox&&) = delete;
        WindowsSandbox& operator=(const WindowsSandbox&) = delete;
        WindowsSandbox& operator=(WindowsSandbox&&) = delete;

        [[nodiscard]] Submission checkReadiness(CompletionHandler<::ai::openai::codex::typed::WindowsSandboxReadinessResponse> handler);
        [[nodiscard]] Submission startSetup(::ai::openai::codex::typed::WindowsSandboxSetupStartParams parameters, CompletionHandler<::ai::openai::codex::typed::WindowsSandboxSetupStartResponse> handler);

    private:
        friend class Client;
        explicit WindowsSandbox(Client& owner) noexcept
            : client(&owner) {
        }
        Client* client;
    };
} // namespace ai::openai::codex::frontend::client
// clang-format on

#endif // AI_OPENAI_CODEX_FRONTEND_CLIENT_WINDOWSSANDBOX_H
